// src/lib/products.ts
// Product model interface and comprehensive mock dataset for Style AI — real clothing imagery via Unsplash CDN

export interface Product {
  id: string;
  name: string;
  description: string;
  category: string;
  price: number;
  images: string[];
  availableSizes: string[];
  sizes?: string[];
  colors: string[];
  fabric: string;
  comfortScore: number;
  skinSafetyScore: number;
  skinSafety?: "SAFE" | "MODERATE" | "AVOID";
  bodyFitScore: number;
  trendScore: number;
  sustainabilityScore: number;
  ecoScore?: number;
  suitableWeather: string[];
  stock: number;
  tags?: string[];
  emoji?: string;
  originalPrice?: number;
}

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "p1",
    name: "Azure French Linen Shirt",
    description: "Crafted from 100% sustainably-harvested French flax linen. Open-weave structure allows maximum airflow, keeping sensitive skin cool and irritation-free in high heat.",
    category: "Summer",
    price: 1499,
    originalPrice: 2199,
    images: [
      "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1588636310486-3a5e2ab60d99?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1596755389378-7fd0c1c58f21?w=800&auto=format&fit=crop&q=80"
    ],
    availableSizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Azure Blue", "Ivory White", "Sage Green"],
    fabric: "100% French Linen",
    comfortScore: 95,
    skinSafetyScore: 97,
    skinSafety: "SAFE",
    bodyFitScore: 92,
    trendScore: 94,
    sustainabilityScore: 98,
    suitableWeather: ["Hot", "Humid", "Summer", "Sunny"],
    stock: 24,
    emoji: "👔",
    tags: ["linen", "summer", "breathable", "sensitive skin"],
  },
  {
    id: "p2",
    name: "GOTS Organic Cotton Hoodie",
    description: "Ultra-soft GOTS-certified organic cotton fleece with zero synthetic dyes. Hypoallergenic micro-brushed lining designed specifically for eczema and sensitive skin.",
    category: "Winter",
    price: 2299,
    originalPrice: 3199,
    images: [
      "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1556821840-4160216167cd?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1620799139507-2a76f79a2f4d?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1556821840-1e5b7213b28b?w=800&auto=format&fit=crop&q=80"
    ],
    availableSizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Charcoal", "Off-White", "Clay Brown"],
    fabric: "100% GOTS Organic Cotton",
    comfortScore: 97,
    skinSafetyScore: 99,
    skinSafety: "SAFE",
    bodyFitScore: 94,
    trendScore: 91,
    sustainabilityScore: 96,
    suitableWeather: ["Cold", "Chilly", "Winter"],
    stock: 18,
    emoji: "🧥",
    tags: ["hoodie", "winter", "organic cotton", "hypoallergenic"],
  },
  {
    id: "p3",
    name: "Bamboo Anti-Chafe Active Tee",
    description: "Naturally antibacterial bamboo viscose blend with four-way stretch. Prevents sweat rash, bacterial growth, and friction chafing during intense workouts.",
    category: "Active",
    price: 899,
    originalPrice: 1299,
    images: [
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1521572208360-fd0d2909a550?w=800&auto=format&fit=crop&q=80"
    ],
    availableSizes: ["S", "M", "L", "XL"],
    colors: ["Slate Black", "Cool Gray", "Forest Green"],
    fabric: "95% Bamboo Viscose, 5% Elastane",
    comfortScore: 98,
    skinSafetyScore: 98,
    skinSafety: "SAFE",
    bodyFitScore: 96,
    trendScore: 89,
    sustainabilityScore: 92,
    suitableWeather: ["Humid", "Warm", "All-Weather"],
    stock: 45,
    emoji: "👕",
    tags: ["activewear", "bamboo", "antibacterial"],
  },
  {
    id: "p4",
    name: "Relaxed Linen Trousers",
    description: "Wide-leg relaxed fit trousers woven from a natural linen and organic cotton blend. Elastic waistband with non-allergenic cotton lining.",
    category: "Summer",
    price: 1899,
    images: [
      "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1594633313217-106540c49ab5?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1594633312415-4cf5bb36141a?w=800&auto=format&fit=crop&q=80"
    ],
    availableSizes: ["28", "30", "32", "34", "36", "38"],
    colors: ["Natural Ecru", "Obsidian Black", "Terracotta"],
    fabric: "55% Linen, 45% Organic Cotton",
    comfortScore: 96,
    skinSafetyScore: 96,
    skinSafety: "SAFE",
    bodyFitScore: 91,
    trendScore: 95,
    sustainabilityScore: 95,
    suitableWeather: ["Hot", "Humid", "Summer"],
    stock: 12,
    emoji: "👖",
    tags: ["trousers", "linen", "relaxed fit"],
  },
  {
    id: "p5",
    name: "Superfine Merino Knit Sweater",
    description: "Superfine 18.5-micron Merino wool engineered below the itch threshold. Provides natural thermal regulation without harsh animal fiber scratchiness.",
    category: "Winter",
    price: 3499,
    originalPrice: 4500,
    images: ["https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["S", "M", "L", "XL"],
    colors: ["Oat Cream", "Navy Blue", "Burgundy"],
    fabric: "100% Superfine Merino Wool",
    comfortScore: 92,
    skinSafetyScore: 84,
    skinSafety: "MODERATE",
    bodyFitScore: 93,
    trendScore: 96,
    sustainabilityScore: 86,
    suitableWeather: ["Cold", "Chilly", "Winter"],
    stock: 8,
    emoji: "🧶",
    tags: ["sweater", "merino", "winter"],
  },
  {
    id: "p6",
    name: "Mulberry Silk Formal Shirt",
    description: "Grade A Mulberry silk containing natural amino acids that actively nourish and preserve the skin barrier overnight and during long formal events.",
    category: "Formal",
    price: 4999,
    images: ["https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["S", "M", "L", "XL"],
    colors: ["Pearl White", "Champagne", "Midnight Black"],
    fabric: "100% Grade A Mulberry Silk",
    comfortScore: 97,
    skinSafetyScore: 96,
    skinSafety: "SAFE",
    bodyFitScore: 95,
    trendScore: 98,
    sustainabilityScore: 84,
    suitableWeather: ["Indoor AC", "Moderate", "Evening"],
    stock: 6,
    emoji: "✨",
    tags: ["formal", "silk", "luxury"],
  },
  {
    id: "p7",
    name: "Tencel Lyocell Casual Joggers",
    description: "Silky smooth Tencel produced in a 99.5% closed-loop solvent recycling process. Wrinkle-resistant with a fluid drape that minimizes mechanical thigh friction.",
    category: "Active",
    price: 1599,
    originalPrice: 2100,
    images: ["https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Stone Gray", "Olive Green", "Black"],
    fabric: "100% Tencel Lyocell",
    comfortScore: 95,
    skinSafetyScore: 95,
    skinSafety: "SAFE",
    bodyFitScore: 94,
    trendScore: 92,
    sustainabilityScore: 96,
    suitableWeather: ["Moderate", "Humid", "Indoor"],
    stock: 30,
    emoji: "🏃",
    tags: ["joggers", "tencel", "active"],
  },
  {
    id: "p8",
    name: "Korean Streetwear Heavy Tee",
    description: "Heavyweight 220 GSM ring-spun organic cotton with a boxy Korean silhouette. Dyed with OEKO-TEX Standard 100 safe non-toxic dyes.",
    category: "Casual",
    price: 699,
    originalPrice: 999,
    images: ["https://images.unsplash.com/photo-1571945153237-4929e783af4a?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["S", "M", "L", "XL"],
    colors: ["Washed Beige", "Slate Blue", "Charcoal", "Dusty Rose"],
    fabric: "100% Organic Cotton (220 GSM)",
    comfortScore: 96,
    skinSafetyScore: 99,
    skinSafety: "SAFE",
    bodyFitScore: 90,
    trendScore: 97,
    sustainabilityScore: 95,
    suitableWeather: ["Moderate", "Warm", "All-Weather"],
    stock: 50,
    emoji: "🎽",
    tags: ["streetwear", "heavy tee", "korean"],
  },
  {
    id: "p9",
    name: "Eco Flax Linen Resort Kimono",
    description: "Unbleached pure flax linen cardigan kimono layer. Provides light solar shielding without trapping sweat or humidity.",
    category: "Casual",
    price: 2199,
    images: ["https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["S/M", "L/XL"],
    colors: ["Natural Linen", "Indigo Wash"],
    fabric: "100% Pure Flax Linen",
    comfortScore: 94,
    skinSafetyScore: 98,
    skinSafety: "SAFE",
    bodyFitScore: 88,
    trendScore: 96,
    sustainabilityScore: 99,
    suitableWeather: ["Hot", "Sunny", "Summer"],
    stock: 15,
    emoji: "👘",
    tags: ["kimono", "linen", "resort"],
  },
  {
    id: "p10",
    name: "Zero-Dye Seamless Organic Socks",
    description: "Undyed GOTS certified organic cotton socks with seamless toe closure. Prevents pressure friction and allergic dye reactions for sensitive feet.",
    category: "Casual",
    price: 349,
    images: ["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["Free Size (6-11)"],
    colors: ["Natural Cream"],
    fabric: "98% Organic Cotton, 2% Elastane",
    comfortScore: 99,
    skinSafetyScore: 100,
    skinSafety: "SAFE",
    bodyFitScore: 98,
    trendScore: 80,
    sustainabilityScore: 98,
    suitableWeather: ["All-Weather"],
    stock: 100,
    emoji: "🧦",
    tags: ["socks", "organic cotton", "seamless"],
  },
  // ─── Additional 40 curated garments to reach 50+ suggestions ───
  {
    id: "p11",
    name: "Cloud Wash Organic Denim Jacket",
    description: "Stone-washed organic cotton denim with zero synthetic indigo. Soft-brushed interior prevents neck and wrist abrasion.",
    category: "Casual",
    price: 2599,
    originalPrice: 3399,
    images: ["https://images.unsplash.com/photo-1544441893-675973e31985?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Cloud Wash", "Midnight Indigo", "Vintage Stone"],
    fabric: "100% Organic Cotton Denim",
    comfortScore: 91,
    skinSafetyScore: 92,
    skinSafety: "SAFE",
    bodyFitScore: 90,
    trendScore: 95,
    sustainabilityScore: 90,
    suitableWeather: ["Moderate", "Cool", "All-Weather"],
    stock: 22,
    emoji: "🧥",
    tags: ["denim", "jacket", "organic cotton"],
  },
  {
    id: "p12",
    name: "Brushed Organic Flannel Shirt",
    description: "Double-brushed organic cotton flannel with peach-skin handfeel. Ideal for layering without trapping heat on sensitive skin.",
    category: "Winter",
    price: 1799,
    images: ["https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Rust Check", "Forest Plaid", "Cream Stripe"],
    fabric: "100% Organic Cotton Flannel",
    comfortScore: 94,
    skinSafetyScore: 96,
    skinSafety: "SAFE",
    bodyFitScore: 88,
    trendScore: 90,
    sustainabilityScore: 91,
    suitableWeather: ["Cold", "Cool", "Winter"],
    stock: 19,
    emoji: "👔",
    tags: ["flannel", "winter", "brushed cotton"],
  },
  {
    id: "p13",
    name: "Sea Salt Linen Shorts",
    description: "Garment-dyed French linen shorts with elasticated waist and coconut-button closure. Salt-washed for immediate softness.",
    category: "Summer",
    price: 1299,
    images: ["https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["28", "30", "32", "34", "36"],
    colors: ["Sea Salt", "Terracotta", "Olive"],
    fabric: "100% French Linen",
    comfortScore: 96,
    skinSafetyScore: 98,
    skinSafety: "SAFE",
    bodyFitScore: 89,
    trendScore: 93,
    sustainabilityScore: 97,
    suitableWeather: ["Hot", "Humid", "Summer"],
    stock: 31,
    emoji: "🩳",
    tags: ["shorts", "linen", "summer"],
  },
  {
    id: "p14",
    name: "Coastal Hemp Blend Tee",
    description: "Hemp and organic cotton jersey with natural UV resistance and antimicrobial properties for coastal humidity.",
    category: "Casual",
    price: 849,
    images: ["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Natural Hemp", "Ocean Blue", "Sand"],
    fabric: "55% Hemp, 45% Organic Cotton",
    comfortScore: 95,
    skinSafetyScore: 97,
    skinSafety: "SAFE",
    bodyFitScore: 90,
    trendScore: 88,
    sustainabilityScore: 99,
    suitableWeather: ["Hot", "Humid", "Summer"],
    stock: 42,
    emoji: "👕",
    tags: ["hemp", "tee", "sustainable"],
  },
  {
    id: "p15",
    name: "Alpine Wool Blend Beanie",
    description: "Traceable extra-fine Merino and organic cotton knit beanie with fleeced inner band for forehead comfort.",
    category: "Winter",
    price: 799,
    images: ["https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["One Size"],
    colors: ["Alpine Grey", "Cream", "Navy"],
    fabric: "50% Merino Wool, 50% Organic Cotton",
    comfortScore: 90,
    skinSafetyScore: 87,
    skinSafety: "MODERATE",
    bodyFitScore: 92,
    trendScore: 89,
    sustainabilityScore: 88,
    suitableWeather: ["Cold", "Winter", "Windy"],
    stock: 60,
    emoji: "🧶",
    tags: ["beanie", "wool", "winter"],
  },
  {
    id: "p16",
    name: "Noir Silk Twill Tie Set",
    description: "Hand-rolled Mulberry silk twill with hypoallergenic silk lining. For sensitive necks during long formal events.",
    category: "Formal",
    price: 1899,
    originalPrice: 2499,
    images: ["https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["One Size"],
    colors: ["Noir", "Burgundy", "Midnight Blue"],
    fabric: "100% Mulberry Silk Twill",
    comfortScore: 92,
    skinSafetyScore: 95,
    skinSafety: "SAFE",
    bodyFitScore: 88,
    trendScore: 92,
    sustainabilityScore: 80,
    suitableWeather: ["Indoor", "Evening", "Formal"],
    stock: 14,
    emoji: "👔",
    tags: ["formal", "silk", "tie"],
  },
  {
    id: "p17",
    name: "Urban Tencel Blazer",
    description: "Unstructured Tencel blazer with organic cotton canvas. Breathable shoulder without synthetic padding that traps heat.",
    category: "Formal",
    price: 4299,
    originalPrice: 5599,
    images: ["https://images.unsplash.com/photo-1594938291221-94f0a3901c02?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["S", "M", "L", "XL"],
    colors: ["Charcoal", "Warm Taupe", "Forest"],
    fabric: "70% Tencel Lyocell, 30% Organic Cotton",
    comfortScore: 93,
    skinSafetyScore: 96,
    skinSafety: "SAFE",
    bodyFitScore: 95,
    trendScore: 96,
    sustainabilityScore: 94,
    suitableWeather: ["Moderate", "Indoor AC", "Formal"],
    stock: 9,
    emoji: "🧥",
    tags: ["blazer", "tencel", "formal"],
  },
  {
    id: "p18",
    name: "Desert Linen Maxi Dress",
    description: "Flowy pure linen maxi with racerback ventilation and side slits for airflow on extremely sensitive lower-leg skin.",
    category: "Summer",
    price: 2699,
    images: ["https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Desert Sand", "Ecru", "Terracotta"],
    fabric: "100% Pure Flax Linen",
    comfortScore: 97,
    skinSafetyScore: 98,
    skinSafety: "SAFE",
    bodyFitScore: 93,
    trendScore: 95,
    sustainabilityScore: 99,
    suitableWeather: ["Hot", "Sunny", "Summer"],
    stock: 11,
    emoji: "👗",
    tags: ["dress", "linen", "summer"],
  },
  {
    id: "p19",
    name: "Forest Bamboo Fleece Hoodie",
    description: "Bamboo fleece with cotton face and bamboo interior — warm without acrylic itch, fully breathable.",
    category: "Winter",
    price: 2199,
    images: ["https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["S", "M", "L", "XL"],
    colors: ["Forest", "Ash Grey", "Deep Navy"],
    fabric: "60% Bamboo Viscose, 40% Organic Cotton Fleece",
    comfortScore: 96,
    skinSafetyScore: 97,
    skinSafety: "SAFE",
    bodyFitScore: 92,
    trendScore: 90,
    sustainabilityScore: 92,
    suitableWeather: ["Cold", "Chilly", "Winter"],
    stock: 17,
    emoji: "🧥",
    tags: ["hoodie", "bamboo", "fleece"],
  },
  {
    id: "p20",
    name: "Clay Modal Lounge Set",
    description: "MicroModal Air jersey loungewear derived from beechwood pulp. Butter-soft against eczema-prone skin.",
    category: "Casual",
    price: 1999,
    images: ["https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Clay", "Stone", "Hazel"],
    fabric: "95% Lenzing MicroModal, 5% Elastane",
    comfortScore: 98,
    skinSafetyScore: 98,
    skinSafety: "SAFE",
    bodyFitScore: 94,
    trendScore: 87,
    sustainabilityScore: 90,
    suitableWeather: ["Indoor", "Moderate", "All-Weather"],
    stock: 25,
    emoji: "👚",
    tags: ["lounge", "modal", "comfort"],
  },
  {
    id: "p21",
    name: "Harbor Striped Breton Top",
    description: "Compact organic cotton Breton stripe with reinforced shoulder seams for sensitive collarbone pressure points.",
    category: "Casual",
    price: 1199,
    images: ["https://images.unsplash.com/photo-1529139574466-a303027c1d8b?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Harbor Stripe", "Ink Stripe", "Ecru Stripe"],
    fabric: "100% Organic Cotton",
    comfortScore: 93,
    skinSafetyScore: 97,
    skinSafety: "SAFE",
    bodyFitScore: 90,
    trendScore: 92,
    sustainabilityScore: 93,
    suitableWeather: ["Moderate", "Cool", "Spring"],
    stock: 28,
    emoji: "👕",
    tags: ["breton", "stripe", "cotton"],
  },
  {
    id: "p22",
    name: "Stone Washed Hemp Chinos",
    description: "Hemp-organic cotton twill chinos with garment-dyed stone wash. Durable thigh without synthetic sheen.",
    category: "Casual",
    price: 2099,
    images: ["https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["28", "30", "32", "34", "36", "38"],
    colors: ["Stone", "Olive", "Khaki"],
    fabric: "60% Hemp, 40% Organic Cotton Twill",
    comfortScore: 92,
    skinSafetyScore: 96,
    skinSafety: "SAFE",
    bodyFitScore: 92,
    trendScore: 90,
    sustainabilityScore: 97,
    suitableWeather: ["Moderate", "Warm", "All-Weather"],
    stock: 16,
    emoji: "👖",
    tags: ["chinos", "hemp", "casual"],
  },
  {
    id: "p23",
    name: "Arctic Thermal Linen Shirt",
    description: "Brushed linen-cotton hybrid for winter sun: insulating yet breathable for temperature swings.",
    category: "Winter",
    price: 1899,
    images: ["https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["S", "M", "L", "XL"],
    colors: ["Arctic Blue", "Snow White", "Heather Grey"],
    fabric: "60% Linen, 40% Organic Cotton Brushed",
    comfortScore: 91,
    skinSafetyScore: 94,
    skinSafety: "SAFE",
    bodyFitScore: 89,
    trendScore: 88,
    sustainabilityScore: 92,
    suitableWeather: ["Cold", "Sunny Winter", "Cool"],
    stock: 13,
    emoji: "👔",
    tags: ["thermal", "linen", "winter"],
  },
  {
    id: "p24",
    name: "Midnight Tuxedo Silk Shirt",
    description: "Pleated bib front Mulberry silk tuxedo shirt with French cuffs and mother-of-pearl buttons.",
    category: "Formal",
    price: 5499,
    images: ["https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["S", "M", "L", "XL"],
    colors: ["Midnight White", "Ivory"],
    fabric: "100% Mulberry Silk",
    comfortScore: 96,
    skinSafetyScore: 97,
    skinSafety: "SAFE",
    bodyFitScore: 96,
    trendScore: 99,
    sustainabilityScore: 82,
    suitableWeather: ["Evening", "Indoor AC", "Formal"],
    stock: 5,
    emoji: "👔",
    tags: ["tuxedo", "formal", "silk"],
  },
  {
    id: "p25",
    name: "Sprint Bamboo Training Shorts",
    description: "Lightweight bamboo-elastane training shorts with laser-cut vents and no inner mesh chafe.",
    category: "Active",
    price: 999,
    images: ["https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Onyx", "Sage", "Cobalt"],
    fabric: "90% Bamboo Viscose, 10% Elastane",
    comfortScore: 97,
    skinSafetyScore: 96,
    skinSafety: "SAFE",
    bodyFitScore: 95,
    trendScore: 90,
    sustainabilityScore: 91,
    suitableWeather: ["Hot", "Humid", "Active"],
    stock: 38,
    emoji: "🩳",
    tags: ["shorts", "training", "bamboo"],
  },
  {
    id: "p26",
    name: "Canvas Organic Cotton Tote Dress",
    description: "Heavy canvas cotton shift dress with deep pockets and zero lining friction on thighs.",
    category: "Summer",
    price: 2299,
    images: ["https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Canvas Ecru", "Clay", "Indigo"],
    fabric: "100% Organic Canvas Cotton",
    comfortScore: 94,
    skinSafetyScore: 97,
    skinSafety: "SAFE",
    bodyFitScore: 90,
    trendScore: 91,
    sustainabilityScore: 94,
    suitableWeather: ["Warm", "Sunny", "Summer"],
    stock: 14,
    emoji: "👗",
    tags: ["dress", "canvas", "summer"],
  },
  {
    id: "p27",
    name: "Haven Modal Sleep Shirt",
    description: "Sateen-woven Modal sleep shirt with flat-felled seams to eliminate shoulder ridge irritation.",
    category: "Casual",
    price: 1499,
    images: ["https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["S", "M", "L", "XL"],
    colors: ["Haven Blue", "Shell Pink", "Moon Grey"],
    fabric: "100% Lenzing Modal Sateen",
    comfortScore: 99,
    skinSafetyScore: 98,
    skinSafety: "SAFE",
    bodyFitScore: 93,
    trendScore: 85,
    sustainabilityScore: 88,
    suitableWeather: ["Indoor", "Night", "All-Weather"],
    stock: 20,
    emoji: "👚",
    tags: ["sleepwear", "modal", "soft"],
  },
  {
    id: "p28",
    name: "Trek Hemp Cargo Pants",
    description: "Triple-stitched hemp canvas cargos with ventilation gussets for humid trekking conditions.",
    category: "Active",
    price: 2399,
    images: ["https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["28", "30", "32", "34", "36", "38"],
    colors: ["Trek Olive", "Sand", "Graphite"],
    fabric: "100% Hemp Canvas",
    comfortScore: 91,
    skinSafetyScore: 96,
    skinSafety: "SAFE",
    bodyFitScore: 93,
    trendScore: 89,
    sustainabilityScore: 99,
    suitableWeather: ["Hot", "Humid", "Outdoor"],
    stock: 18,
    emoji: "👖",
    tags: ["cargo", "hemp", "outdoor"],
  },
  {
    id: "p29",
    name: "Luxe Cashmere Blend Scarf",
    description: "Certified Mongolian cashmere and Mulberry silk blend scarf, hand-finished edge without chemical stiffener.",
    category: "Winter",
    price: 3299,
    images: ["https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["One Size"],
    colors: ["Luxe Camel", "Charcoal", "Blush"],
    fabric: "70% Cashmere, 30% Mulberry Silk",
    comfortScore: 95,
    skinSafetyScore: 88,
    skinSafety: "MODERATE",
    bodyFitScore: 90,
    trendScore: 94,
    sustainabilityScore: 78,
    suitableWeather: ["Cold", "Windy", "Winter"],
    stock: 12,
    emoji: "🧣",
    tags: ["scarf", "cashmere", "winter"],
  },
  {
    id: "p30",
    name: "Boardwalk Hemp Camp Shirt",
    description: "Boxy hemp camp collar shirt with corozo nut buttons and loop ventilation on back yoke.",
    category: "Summer",
    price: 1699,
    images: ["https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["S", "M", "L", "XL"],
    colors: ["Boardwalk Stripe", "Natural", "Washed Navy"],
    fabric: "100% Hemp",
    comfortScore: 94,
    skinSafetyScore: 96,
    skinSafety: "SAFE",
    bodyFitScore: 89,
    trendScore: 93,
    sustainabilityScore: 99,
    suitableWeather: ["Hot", "Humid", "Summer"],
    stock: 21,
    emoji: "👔",
    tags: ["camp shirt", "hemp", "summer"],
  },
  {
    id: "p31",
    name: "Studio Tencel Wrap Blouse",
    description: "Wrap-front Tencel blouse with bias-cut silk-like drape but fully machine washable.",
    category: "Formal",
    price: 2199,
    images: ["https://images.unsplash.com/photo-1594938291221-94f0a3901c02?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["XS", "S", "M", "L"],
    colors: ["Studio White", "Petal Pink", "Slate"],
    fabric: "100% Tencel Lyocell Satin",
    comfortScore: 96,
    skinSafetyScore: 97,
    skinSafety: "SAFE",
    bodyFitScore: 94,
    trendScore: 96,
    sustainabilityScore: 96,
    suitableWeather: ["Indoor AC", "Moderate", "Formal"],
    stock: 10,
    emoji: "👚",
    tags: ["blouse", "tencel", "formal"],
  },
  {
    id: "p32",
    name: "Velocity Bamboo压缩 Shorts",
    description: "High-compression bamboo training tights with flatlock seams for marathon chafe prevention.",
    category: "Active",
    price: 1399,
    images: ["https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["S", "M", "L", "XL"],
    colors: ["Velocity Black", "Graphite", "Neon Edge"],
    fabric: "85% Bamboo Viscose, 15% Elastane",
    comfortScore: 97,
    skinSafetyScore: 95,
    skinSafety: "SAFE",
    bodyFitScore: 97,
    trendScore: 91,
    sustainabilityScore: 89,
    suitableWeather: ["Active", "Humid", "Warm"],
    stock: 33,
    emoji: "🩳",
    tags: ["compression", "bamboo", "active"],
  },
  {
    id: "p33",
    name: "Cottage Linen Smock Dress",
    description: "Gathered linen smock with 3/4 sleeves and underarm vents for cottage humidity and kitchen heat.",
    category: "Summer",
    price: 1899,
    images: ["https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["XS", "S", "M", "L"],
    colors: ["Cottage White", "Sage", "Dusty Rose"],
    fabric: "100% French Linen",
    comfortScore: 95,
    skinSafetyScore: 97,
    skinSafety: "SAFE",
    bodyFitScore: 90,
    trendScore: 91,
    sustainabilityScore: 98,
    suitableWeather: ["Hot", "Humid", "Summer"],
    stock: 15,
    emoji: "👗",
    tags: ["smock", "linen", "summer"],
  },
  {
    id: "p34",
    name: "Wool-Mix Tailored Culottes",
    description: "Wool-flax tailored culottes with organic cotton lining on seat for seated office comfort.",
    category: "Formal",
    price: 2799,
    images: ["https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Tailor Grey", "Navy", "Camel"],
    fabric: "60% Wool, 40% Flax Linen + Cotton lining",
    comfortScore: 89,
    skinSafetyScore: 85,
    skinSafety: "MODERATE",
    bodyFitScore: 93,
    trendScore: 94,
    sustainabilityScore: 83,
    suitableWeather: ["Cool", "Indoor AC", "Formal"],
    stock: 7,
    emoji: "👖",
    tags: ["culottes", "wool", "formal"],
  },
  {
    id: "p35",
    name: "Breeze Linen-Cotton Polo",
    description: "Piqué knit linen-cotton polo with zero elastane collar to avoid neck imprint itch.",
    category: "Casual",
    price: 1199,
    images: ["https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Breeze White", "Pacific Blue", "Moss"],
    fabric: "55% Linen, 45% Organic Cotton Piqué",
    comfortScore: 93,
    skinSafetyScore: 96,
    skinSafety: "SAFE",
    bodyFitScore: 91,
    trendScore: 89,
    sustainabilityScore: 93,
    suitableWeather: ["Warm", "Moderate", "Casual"],
    stock: 29,
    emoji: "👕",
    tags: ["polo", "linen", "casual"],
  },
  {
    id: "p36",
    name: "Cozy Organic Terry Shorts",
    description: "French terry organic cotton loopback shorts with hidden phone pocket inside non-chafe seam.",
    category: "Active",
    price: 899,
    images: ["https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["S", "M", "L", "XL"],
    colors: ["Cozy Grey", "Heather Oat", "Navy"],
    fabric: "100% Organic Cotton Terry",
    comfortScore: 95,
    skinSafetyScore: 98,
    skinSafety: "SAFE",
    bodyFitScore: 90,
    trendScore: 86,
    sustainabilityScore: 94,
    suitableWeather: ["Warm", "Active", "Casual"],
    stock: 41,
    emoji: "🩳",
    tags: ["terry", "shorts", "organic"],
  },
  {
    id: "p37",
    name: "Heritage Selvedge Jeans",
    description: "Organic selvedge denim with unsanforized natural indigo and no chemical stretch for authentic thigh drape.",
    category: "Casual",
    price: 2899,
    images: ["https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["28", "30", "32", "34", "36", "38"],
    colors: ["Heritage Indigo", "Natural Rinse"],
    fabric: "100% Organic Selvedge Denim",
    comfortScore: 88,
    skinSafetyScore: 91,
    skinSafety: "SAFE",
    bodyFitScore: 93,
    trendScore: 96,
    sustainabilityScore: 90,
    suitableWeather: ["Moderate", "Cool", "All-Weather"],
    stock: 20,
    emoji: "👖",
    tags: ["jeans", "selvedge", "denim"],
  },
  {
    id: "p38",
    name: "Feather Linen Resort Shirt",
    description: "Featherweight linen voile resort shirt with French seams for shoulder blade comfort.",
    category: "Summer",
    price: 1599,
    images: ["https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["S", "M", "L", "XL"],
    colors: ["Feather White", "Sky", "Palm Print"],
    fabric: "100% Linen Voile",
    comfortScore: 95,
    skinSafetyScore: 98,
    skinSafety: "SAFE",
    bodyFitScore: 90,
    trendScore: 94,
    sustainabilityScore: 98,
    suitableWeather: ["Hot", "Humid", "Resort"],
    stock: 17,
    emoji: "👔",
    tags: ["resort", "linen", "voile"],
  },
  {
    id: "p39",
    name: "Pinnacle Merino Base Layer",
    description: "17.5-micron non-mulesed Merino base layer for alpine sports with itch-free next-to-skin wear.",
    category: "Active",
    price: 1999,
    images: ["https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["S", "M", "L", "XL"],
    colors: ["Pinnacle Black", "Ice Grey", "Alpine Blue"],
    fabric: "100% 17.5-micron Merino",
    comfortScore: 92,
    skinSafetyScore: 86,
    skinSafety: "MODERATE",
    bodyFitScore: 95,
    trendScore: 92,
    sustainabilityScore: 84,
    suitableWeather: ["Cold", "Snow", "Active Winter"],
    stock: 11,
    emoji: "🧶",
    tags: ["base layer", "merino", "active"],
  },
  {
    id: "p40",
    name: "Silk Emulsion Slip Dress",
    description: "Bias-cut 19-momme silk satin slip with hidden French seams for night-time skin recovery.",
    category: "Formal",
    price: 3999,
    images: ["https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["XS", "S", "M", "L"],
    colors: ["Emulsion Pink", "Champagne", "Black Satin"],
    fabric: "100% 19-momme Mulberry Silk Satin",
    comfortScore: 98,
    skinSafetyScore: 97,
    skinSafety: "SAFE",
    bodyFitScore: 94,
    trendScore: 98,
    sustainabilityScore: 81,
    suitableWeather: ["Evening", "Indoor", "Formal"],
    stock: 6,
    emoji: "👗",
    tags: ["slip dress", "silk", "evening"],
  },
  {
    id: "p41",
    name: "Utility Organic Canvas Jacket",
    description: "Four-pocket organic canvas chore jacket with triple-needle stitching and removable organic fleece liner.",
    category: "Winter",
    price: 2699,
    images: ["https://images.unsplash.com/photo-1544441893-675973e31985?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Utility Olive", "Natural Canvas", "Navy"],
    fabric: "100% Organic Canvas + Organic Fleece liner",
    comfortScore: 92,
    skinSafetyScore: 94,
    skinSafety: "SAFE",
    bodyFitScore: 91,
    trendScore: 93,
    sustainabilityScore: 92,
    suitableWeather: ["Cool", "Cold", "Windy"],
    stock: 15,
    emoji: "🧥",
    tags: ["chore jacket", "canvas", "utility"],
  },
  {
    id: "p42",
    name: "Luna Modal Pajama Set",
    description: "Full Modal pajama set with piped collar and shell buttons that never heat against skin.",
    category: "Casual",
    price: 2199,
    images: ["https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["S", "M", "L", "XL"],
    colors: ["Luna Blue", "Cloud White", "Graphite"],
    fabric: "100% Lenzing Modal",
    comfortScore: 99,
    skinSafetyScore: 98,
    skinSafety: "SAFE",
    bodyFitScore: 93,
    trendScore: 86,
    sustainabilityScore: 89,
    suitableWeather: ["Night", "Indoor", "All-Weather"],
    stock: 18,
    emoji: "👚",
    tags: ["pajama", "modal", "sleep"],
  },
  {
    id: "p43",
    name: "Riviera Linen Blend Tee",
    description: "Slubby linen-cotton blend tee with curved hem and side vents for Riviera coast heat.",
    category: "Summer",
    price: 999,
    images: ["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Riviera White", "Marina Blue", "Sunset Orange"],
    fabric: "55% Linen, 45% Organic Cotton Slub",
    comfortScore: 95,
    skinSafetyScore: 97,
    skinSafety: "SAFE",
    bodyFitScore: 89,
    trendScore: 91,
    sustainabilityScore: 95,
    suitableWeather: ["Hot", "Sunny", "Coastal"],
    stock: 35,
    emoji: "👕",
    tags: ["tee", "linen", "riviera"],
  },
  {
    id: "p44",
    name: "Summit Hemp Puffer Vest",
    description: "Recycled hemp-fill puffer vest with organic cotton shell — warm without polyester itch on chest.",
    category: "Winter",
    price: 2999,
    images: ["https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["S", "M", "L", "XL"],
    colors: ["Summit Black", "Alpine Green", "Stone"],
    fabric: "Shell: Organic Cotton, Fill: Hemp fiber",
    comfortScore: 91,
    skinSafetyScore: 93,
    skinSafety: "SAFE",
    bodyFitScore: 90,
    trendScore: 92,
    sustainabilityScore: 93,
    suitableWeather: ["Cold", "Windy", "Winter"],
    stock: 13,
    emoji: "🦺",
    tags: ["puffer", "vest", "hemp"],
  },
  {
    id: "p45",
    name: "Orchid Tencel Midi Skirt",
    description: "Liquid-drape Tencel midi with A-line cut and silk-like glide without under-skirt static.",
    category: "Formal",
    price: 1899,
    images: ["https://images.unsplash.com/photo-1581044777550-4cfa60707c03?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["XS", "S", "M", "L"],
    colors: ["Orchid", "Sage", "Black"],
    fabric: "100% Tencel Lyocell Twill",
    comfortScore: 94,
    skinSafetyScore: 96,
    skinSafety: "SAFE",
    bodyFitScore: 93,
    trendScore: 94,
    sustainabilityScore: 96,
    suitableWeather: ["Moderate", "Indoor AC", "Formal"],
    stock: 9,
    emoji: "👗",
    tags: ["midi skirt", "tencel", "formal"],
  },
  {
    id: "p46",
    name: "Trail Bamboo Vent Tee",
    description: "Ultralight bamboo tee with back mesh insert and flat seams for trail running ventilation.",
    category: "Active",
    price: 799,
    images: ["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["S", "M", "L", "XL"],
    colors: ["Trail Lime", "Earth Brown", "Slate"],
    fabric: "92% Bamboo Viscose, 8% Elastane Mesh",
    comfortScore: 97,
    skinSafetyScore: 97,
    skinSafety: "SAFE",
    bodyFitScore: 96,
    trendScore: 88,
    sustainabilityScore: 90,
    suitableWeather: ["Hot", "Active", "Trail"],
    stock: 44,
    emoji: "👕",
    tags: ["trail", "bamboo", "ventilated"],
  },
  {
    id: "p47",
    name: "Harvest Organic Corduroy Overshirt",
    description: "8-wale organic corduroy overshirt with moleskin handfeel and no synthetic pile.",
    category: "Winter",
    price: 2399,
    images: ["https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["S", "M", "L", "XL"],
    colors: ["Harvest Rust", "Moss", "Natural"],
    fabric: "100% Organic Corduroy Cotton",
    comfortScore: 92,
    skinSafetyScore: 94,
    skinSafety: "SAFE",
    bodyFitScore: 90,
    trendScore: 93,
    sustainabilityScore: 91,
    suitableWeather: ["Cool", "Cold", "Autumn"],
    stock: 16,
    emoji: "👔",
    tags: ["corduroy", "overshirt", "organic"],
  },
  {
    id: "p48",
    name: "Airy Linen Gauze Shirt",
    description: "Double-gauze French linen shirt with crinkle texture that never clings to damp skin.",
    category: "Summer",
    price: 1399,
    images: ["https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Airy White", "Fog", "Powder Blue"],
    fabric: "100% Linen Gauze",
    comfortScore: 96,
    skinSafetyScore: 98,
    skinSafety: "SAFE",
    bodyFitScore: 88,
    trendScore: 92,
    sustainabilityScore: 98,
    suitableWeather: ["Hot", "Humid", "Gauze"],
    stock: 20,
    emoji: "👔",
    tags: ["gauze", "linen", "airy"],
  },
  {
    id: "p49",
    name: "Essential Bamboo Boxer Briefs 3-Pack",
    description: "Seamless bamboo boxers with zero-dye elastic — prevents waistband itch and thigh chafe.",
    category: "Casual",
    price: 999,
    originalPrice: 1499,
    images: ["https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["S", "M", "L", "XL"],
    colors: ["Essential Natural", "Black", "Grey"],
    fabric: "95% Bamboo Viscose, 5% Elastane",
    comfortScore: 98,
    skinSafetyScore: 99,
    skinSafety: "SAFE",
    bodyFitScore: 97,
    trendScore: 82,
    sustainabilityScore: 92,
    suitableWeather: ["All-Weather", "Daily"],
    stock: 80,
    emoji: "🩲",
    tags: ["underwear", "bamboo", "essential"],
  },
  {
    id: "p50",
    name: "Monsoon Hemp Rain Poncho",
    description: "Wax-coated hemp poncho with organic cotton lining for breathable monsoon protection without PVC off-gassing.",
    category: "Winter",
    price: 2799,
    images: ["https://images.unsplash.com/photo-1544441893-675973e31985?w=800&auto=format&fit=crop&q=80"],
    availableSizes: ["One Size"],
    colors: ["Monsoon Olive", "Mustard", "Midnight"],
    fabric: "100% Waxed Hemp + Cotton lining",
    comfortScore: 88,
    skinSafetyScore: 92,
    skinSafety: "SAFE",
    bodyFitScore: 89,
    trendScore: 90,
    sustainabilityScore: 96,
    suitableWeather: ["Rainy", "Monsoon", "Humid"],
    stock: 10,
    emoji: "🧥",
    tags: ["rain", "hemp", "poncho"],
  },
];

export const CATEGORIES = ["All", "Summer", "Winter", "Active", "Formal", "Casual"];

export const FABRICS = [
  "All",
  "100% French Linen",
  "100% GOTS Organic Cotton",
  "95% Bamboo Viscose, 5% Elastane",
  "55% Linen, 45% Organic Cotton",
  "100% Superfine Merino Wool",
  "100% Grade A Mulberry Silk",
  "100% Tencel Lyocell",
  "100% Pure Flax Linen",
  "55% Hemp, 45% Organic Cotton",
  "100% Hemp",
  "100% Lenzing Modal",
];

export const PRODUCTS = MOCK_PRODUCTS;
